theme: jekyll-theme-minimal

#theme: jekyll-theme-hacker
#theme: minima

title: Grupo de Estudio de Movilidad de Montevideo
#description: A short description

#plugins:
#- jekyll-menus
#menus:
#  header:
#    title: Home
#    weight: 1

sidebar:
  title: "Sample Title"
  nav: sidebar-sample
